### ISSUE TITLE
Compilation fails after Espressif32 platform update

### ISSUE THREAD

**Issue by helgef** [armageddon421/electrodacus-esp32#37]
Code no longer compiles on Espressif platform updated to 5.1.0:

Compiling .pio/build/serial/esp32-hal-dac.o
Compiling .pio/build/serial/esp32-hal-gpio.o
In file included from /Users/helge/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-cpu.c:22:
/Users/helge/.platformio/packages/framework-espidf/components/soc/esp32/include/soc/rtc.h:22:14: error: expected identifier or '(' before numeric constant
 #define MHZ (1000000)
              ^~~~~~~
/Users/helge/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-cpu.c:47:16: note: in expansion of macro 'MHZ'
 const uint32_t MHZ = 1000000;
                ^~~
*** [.pio/build/serial/esp32-hal-cpu.o] Error 1
/Users/helge/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.c: In function '__pinMode':
/Users/helge/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.c:102:24: error: 'rtc_gpio_desc' undeclared (first use in this function); did you mean 'rtc_io_desc'?
     uint32_t rtc_reg = rtc_gpio_desc[pin].reg;
                        ^~~~~~~~~~~~~
                        rtc_io_desc
/Users/helge/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.c:102:24: note: each undeclared identifier is reported only once for each function it appears in
*** [.pio/build/serial/esp32-hal-gpio.o] Error 1
============================== [FAILED] Took 79.68 seconds ==============================

Environment    Status    Duration
-------------  --------  ------------
serial         FAILED    00:01:19.685
========================= 1 failed, 0 succeeded in 00:01:19.685 ================

Changing platform version to 4.4.0 (a few weeks old) in platformio.ini worked for me:

...
[env]
platform = espressif32@4.4.0
board = nodemcu-32s
...

**Comment by helgef** [comment]
Seems like its some dependencies from the ESP Async Webserver that causing the issues. Using the current development branch from their github also works, so this problem will probably sort itself out once PlatformIO updates the package
